/**
 * Read-only user activity page inside account settings.
 */
'use client';

import { useDeferredValue, useEffect, useMemo, useState } from 'react';
import {
    getUserActivityApi,
    type UserActivityCategory,
    type UserActivityItem,
    type UserActivityOrder,
    type UserActivityResponse,
} from '@/api/users';
import { AppLoadingState } from '@/components/ui';
import { useApi } from '@/lib/hooks/useApi';
import { usePageTitle } from '@/lib/hooks/usePageTitle';
import styles from './activity-page.module.css';

const PAGE_SIZE = 12;

const CATEGORY_FILTERS: Array<{
    value: UserActivityCategory;
    label: string;
}> = [
    { value: 'all', label: 'All' },
    { value: 'authentication', label: 'Authentication' },
    { value: 'verification', label: 'Verification' },
    { value: 'account', label: 'Account' },
    { value: 'security', label: 'Security' },
];

/**
 * Displays immutable account activity with search, filters, ordering, and pagination.
 */
export default function ActivityPage() {
    usePageTitle('User Activity');

    const [activity, setActivity] = useState<UserActivityResponse | null>(null);
    const [page, setPage] = useState(1);
    const [category, setCategory] = useState<UserActivityCategory>('all');
    const [order, setOrder] = useState<UserActivityOrder>('newest');
    const [search, setSearch] = useState('');
    const deferredSearch = useDeferredValue(search);
    const effectiveSearch = useMemo(() => {
        const trimmed = deferredSearch.trim();
        return trimmed.length >= 3 ? trimmed : undefined;
    }, [deferredSearch]);

    const { execute: fetchActivity, loading, error } = useApi(getUserActivityApi, {
        showErrorToast: false,
        onSuccess: setActivity,
    });

    useEffect(() => {
        void fetchActivity({
            page,
            pageSize: PAGE_SIZE,
            category,
            order,
            search: effectiveSearch,
        });
    }, [category, effectiveSearch, fetchActivity, order, page]);

    const totalPages = activity?.pagination.totalPages ?? 0;

    return (
        <section className={styles.panel} aria-label="User activity">
            <div className={styles.hero}>
                <div>
                    <p className={styles.eyebrow}>User activity</p>
                    <h1>Review every important account action.</h1>
                    <p>
                        This read-only history helps you confirm sign-ins, verification attempts,
                        account changes, and security protections tied to your Gracon account.
                    </p>
                </div>
                <div className={styles.integrityCard}>
                    <span>Read only</span>
                    <strong>Cannot be edited or deleted</strong>
                    <p>Activity is generated by platform security events.</p>
                </div>
            </div>

            <div className={styles.controls} aria-label="Activity controls">
                <label className={styles.searchBox}>
                    <span>Search</span>
                    <input
                        type="search"
                        value={search}
                        onChange={(event) => {
                            setSearch(event.target.value);
                            setPage(1);
                        }}
                        placeholder="Type at least 3 characters..."
                    />
                </label>

                <div className={styles.filters} aria-label="Activity filters">
                    {CATEGORY_FILTERS.map((filter) => (
                        <button
                            key={filter.value}
                            type="button"
                            className={category === filter.value ? styles.filterActive : ''}
                            onClick={() => {
                                setCategory(filter.value);
                                setPage(1);
                            }}
                        >
                            {filter.label}
                        </button>
                    ))}
                </div>

                <label className={styles.orderControl}>
                    <span>Order</span>
                    <select
                        value={order}
                        onChange={(event) => {
                            setOrder(event.target.value as UserActivityOrder);
                            setPage(1);
                        }}
                    >
                        <option value="newest">Newest first</option>
                        <option value="oldest">Oldest first</option>
                    </select>
                </label>
            </div>

            {loading && !activity ? (
                <AppLoadingState
                    variant="panel"
                    minHeight="360px"
                    message="Loading activity..."
                    detail="Reading your account history"
                />
            ) : null}

            {error ? (
                <div className={styles.errorState} role="alert">
                    <strong>Unable to load activity</strong>
                    <p>{error}</p>
                    <button
                        type="button"
                        onClick={() =>
                            void fetchActivity({
                                page,
                                pageSize: PAGE_SIZE,
                                category,
                                order,
                                search: effectiveSearch,
                            })
                        }
                    >
                        Try again
                    </button>
                </div>
            ) : null}

            {!loading && activity && activity.items.length === 0 ? (
                <div className={styles.emptyState}>
                    <strong>No matching activity</strong>
                    <p>Adjust the search, filter, or order to inspect a different part of your history.</p>
                </div>
            ) : null}

            {activity && activity.items.length > 0 ? (
                <>
                    <div className={styles.summaryLine}>
                        <span>
                            Showing {activity.items.length} of {activity.pagination.totalItems} actions
                        </span>
                        <span>Page {activity.pagination.page} of {Math.max(totalPages, 1)}</span>
                    </div>

                    <div className={styles.activityList}>
                        {activity.items.map((item) => (
                            <ActivityRow key={item.id} item={item} />
                        ))}
                    </div>

                    <div className={styles.pagination} aria-label="Activity pagination">
                        <button
                            type="button"
                            disabled={page <= 1 || loading}
                            onClick={() => setPage((current) => Math.max(1, current - 1))}
                        >
                            Previous
                        </button>
                        <span>{page} / {Math.max(totalPages, 1)}</span>
                        <button
                            type="button"
                            disabled={page >= totalPages || loading || totalPages === 0}
                            onClick={() => setPage((current) => current + 1)}
                        >
                            Next
                        </button>
                    </div>
                </>
            ) : null}
        </section>
    );
}

/**
 * Renders one immutable activity record.
 */
function ActivityRow({ item }: { item: UserActivityItem }) {
    return (
        <article className={styles.activityRow}>
            <div className={[styles.tone, styles[`tone-${item.tone}`]].join(' ')} aria-hidden="true" />
            <div className={styles.activityMain}>
                <div className={styles.activityTitleLine}>
                    <h2>{item.title}</h2>
                    <span>{formatCategory(item.category)}</span>
                </div>
                <p>{item.description}</p>
                <div className={styles.activityMeta}>
                    <span>{formatDateTime(item.createdAt)}</span>
                    <span>{item.eventType}</span>
                    <span>{item.ipAddress ?? 'IP not recorded'}</span>
                </div>
            </div>
        </article>
    );
}

/**
 * Formats activity categories for display.
 */
function formatCategory(category: UserActivityItem['category']): string {
    return category
        .split('-')
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join(' ');
}

/**
 * Formats an ISO timestamp into a compact user-facing date and time.
 */
function formatDateTime(value: string): string {
    return new Intl.DateTimeFormat(undefined, {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
    }).format(new Date(value));
}
